# docker-composeのバージョンを指定
version: "3.9"

# baseball_reportのコンテナを作成
services:
  app:
    container_name: bb_api
    build: 
      context: .
      dockerfile: container/Dockerfile
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    # コンテナ正常起動後、entrypoint.shを実行する
    #command: ["sh", "-c", "/entrypoint.sh"]
    tty: true
    stdin_open: true