version: "3.9"

services:
  db:
    image: 675501946988.dkr.ecr.ap-northeast-1.amazonaws.com/baseball_report-db:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bbapi-db
      - MYSQL_USER=bbapi
      - MYSQL_PASSWORD=bbapi-dev
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -ubbapi -pbbapi
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

  app:
    image: 675501946988.dkr.ecr.ap-northeast-1.amazonaws.com/baseball_report-app:latest
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TZ=Asia/Tokyo
