-- MYSQL_USERに権限を付与
GRANT ALL PRIVILEGES ON *.* TO 'bbapi'@'%';
FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS bb_db
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_bin;

USE bb_db;

CREATE TABLE matches (
    id INT AUTO_INCREMENT PRIMARY KEY,
    date DATE NOT NULL,
    home VARCHAR(50) NOT NULL,
    away VARCHAR(50) NOT NULL,
    league VARCHAR(50) NOT NULL,
    stadium VARCHAR(100) NOT NULL,
    starttime TIME NOT NULL,
    UNIQUE KEY link VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE scores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    home_score VARCHAR(3) DEFAULT '0',
    away_score VARCHAR(3) DEFAULT '0',
    batter VARCHAR(30) DEFAULT 'No Batter',
    inning VARCHAR(30) DEFAULT '0回表',
    result VARCHAR(100) DEFAULT '試合前',
    match_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (match_id) REFERENCES matches(id)
);